name = "waalge/test-params"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'waalge/test-params'"

[repository]
user = "waalge"
project = "test-params"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
